name: Project - Todo

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - id: add_to_project
        run: |
          echo "EVENT: ${{ github.event.url }}"
          gh project item-add 2 --owner AidaAP --url xxx
#      - id: checkout
#        name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0 # Required to retrieve tags
#      - uses: ./.github/actions/project-automation
#        with:
#          project: topup-gateway-test
#          column: Todo
#          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
