name: Project - Todo

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to retrieve tags
      - uses: ./.github/actions/project-automation
        with:
          project: topup-gateway-test
          column: Todo
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
