name: Project - Todo

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to retrieve tags
#      - id: add_issue_to_project
#        run: gh issue edit ${{ github.event.issue.number }} --add-project "topup-gateway-test"
      - id: add_to_project
        run: gh project item-add 2 --owner "AidaAP" --url "${{ github.event.issue.url }}"
#      - id: checkout
#        name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0 # Required to retrieve tags
#      - uses: ./.github/actions/project-automation
#        with:
#          project: topup-gateway-test
#          column: Todo
#          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
