name: Project - Todo

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to retrieve tags
      - id: add_issue_to_project
        run: gh issue edit ${{ github.event.issue.number }} --add-project "topup-gateway-test"
      - id: project_view
        run: gh project view 2 --owner "AidaAP"
      - id: list_projects
        run: gh project list --owner "AidaAP"
      - id: list_project_fields
        run: gh project field-list 2 --owner "AidaAP"
      - id: set_issue_id
        run: |
          ISSUE_ID=$(gh project item-list 2 --owner "AidaAP" --format=json | jq '.items[] | select(.content.type=="Issue" and .content.number==${{ github.event.issue.number }}) | .id')
          echo "IID=${ISSUE_ID}" >> $GITHUB_ENV
      - id: echo_1
        run: echo "${ISSUE_ID}"
      - id: echo_2
        run: echo "${IID}"
      - id: list_project_issues
        run: gh issue list --repo "AidaAP/topup-gateway-test"
      - id: set_issue_status_todo
        run: gh project item-edit --id ${{ github.event.issue.number }} --project-id "PVT_kwHOBTQzos4Abz96" --field-id "Status" --text "⏳ Todo"
#      - id: add_to_project
#        run: gh project item-add 2 --owner "AidaAP" --url "${{ github.event.issue.url }}"
#      - id: checkout
#        name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0 # Required to retrieve tags
#      - uses: ./.github/actions/project-automation
#        with:
#          project: topup-gateway-test
#          column: Todo
#          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
