name: Project - Todo

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/project-automation
        with:
          project: topup-gateway-test
          column: Todo
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
